### ISSUE TITLE
"Error: Missing sample normals" when trying fssr after scene2pset

### ISSUE THREAD

**Issue by ajabri** [simonfuhrmann/mve#162]
I'm getting the following error:
```
Floating Scale Surface Reconstruction (built on Aug 19 2015, 02:04:09).
Loading: point-set.ply...
Error: Missing sample normalsError: Missing sample normals
```

Note that this is after I ran:

```
apps/dmrecon/dmrecon scenes/cyc.46_2.dense
apps/scene2pset/scene2pset scenes/cyc.46_2.dense scenes/cyc.46_2.dense-pset.ply
```

Also note that I only managed to compile mve on redhat 6.6 after patching by renameing util/string.h and util/endian.h. But it compiled correctly, from what I can tell.

**Comment by flanggut** [comment]
fssr needs additional information in the point set (most importantly normals and scale) which scene2pset doesn't export by default. You can add this with the  `-F` option:
    scene2pset -F0 scenes/cyc.46_2.dense scenes/cyc.46_2.dense-pset.ply

The actual argument for `-F` is a little bit tricky because dmrecon might reconstruct on different scales. The default is 0 but if some of the images are large (> 1.5 Mpixel) you need to export multiple point sets on different scales. To do this you simply call scene2pset multiple times and merge all of the point sets with fssr:
    scene2pset -F0 scene_directory pset_L0.ply
    scene2pset -F1 scene_directory pset_L1.ply
    scene2pset -F2 scene_directory pset_L2.ply
    scene2pset -F3 scene_directory pset_L3.ply
    fssrecon pset_L0.ply pset_L1.ply pset_L2.ply pset_L3.ply final-output-mesh.ply

We're planning to add another option to scene2pset in the furture that just exports all possible scales, but for now this is what you need to do.

**Comment by ajabri** [comment]
Cool, thanks!
