### ISSUE TITLE
Build issues on OS X

### ISSUE THREAD

**Issue by doersino** [simonfuhrmann/mve#236]
In order to build successfully on OS X (while following the [instructions](https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X)), I had to perform some extra steps:

1. Add the following lines in `Makefile.inc` (around line 7) before running `make`:

   ```bash
   CXXFLAGS += -I/usr/local/include
   LDLIBS += -L/usr/local/lib
   ```
2. Specify the full path to `qmake`, e.g. `/usr/local/Cellar/qt5/5.6.0/bin/qmake`.

I don't know whether this is specific to my setup or if others will run into the same issues, so I thought I'd leave my additions here. Should I add them in the [wiki](https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X)?

**Comment by flanggut** [comment]
1. If homebrew is installed correctly you shouldn't need to specify the include and lib paths. I'm compiling on my installation without making changes to the Makefile. 
2. `qmake` might not be linked automatically by homebrew due to qt4/qt5 version conflicts. As noted in the instructions `brew link --force qt5` should fix this problem.

**Comment by doersino** [comment]
1. As far as I remember, I have installed homebrew according to the instructions. Running `brew doctor` doesn't turn up anything either.
2. True, I overlooked that part.

Seems like these issues are unlikely to affect others, so I'll close this. Thanks!

**Comment by flanggut** [comment]
That's awkward. When you install the Xcode command line tools the include and lib paths in `/usr/local/` should be set automatically.
