### ISSUE TITLE
Initial values for camera extrinsics

### ISSUE THREAD

**Issue by lvk88** [simonfuhrmann/mve#237]
Hello,

is there a way to initialize the bundle adjustment with "roughly" known camera extrinsics (e.g. position and orientation)? In my application, I roughly know the distance between the object and the camera center and also know that the camera moves on an "almost" circular path whose rotational axis lies "almost" where the center of gravity of the object is. In addition, I also know the camera intrinsics.

However, I thought it would be nice to run a bundle adjustment on this known setting to get rid of the "almosts".

Sorry if this is a silly request, I am not so much experienced with photo reconstruction...

**Comment by simonfuhrmann** [comment]
Unfortunately, there is no way to initialize extrinsics. You will still need the features and matching for bundle adjustment. In theory I guess it would be possible to read extrinsics after matching and start from there instead of incremental bundle adjustment, but it's just not implemented. Sorry.

If you're up to it, you can try to hack it in here instead of initial pair selection and incremental reconstruction. You would have to do something like 1) triangulate tracks, 2) remove large error tracks, 3) run bundle adjustment, 4) prune large error tracks, and 5) exit.
https://github.com/simonfuhrmann/mve/blob/master/apps/sfmrecon/sfmrecon.cc#L250
