### ISSUE TITLE
Clarification on pixel footprint function

### ISSUE THREAD

**Issue by sweeneychris** [simonfuhrmann/mve#261]
Could you expand on the intuition behind this method? https://github.com/simonfuhrmann/mve/blob/master/libs/mve/depthmap.h#L80

Am I understanding correctly that this method is computing the depth at a pixel in terms of some sort of pixel or normalized units? 

I am interesting in understanding your code for converting depth maps to meshes, and am interested in the intuition for your depth discontinuity filtering. This method is called in that code: https://github.com/simonfuhrmann/mve/blob/master/libs/mve/depthmap.cc#L288

Thanks!

**Comment by nmoehrle** [comment]
The `pixel_footprint` function calculates the projection size of a pixel given camera model and distance (to the surface - *depth*). It is essentially the same as the [ground sample distance] (https://en.wikipedia.org/wiki/Ground_sample_distance) (distance between to pixel centers projected onto the ground/surface).

The depth discontinuity filtering avoids the creation of triangles for neighboring pixels with very different depth values (probably belong to different surfaces). Since depth maps frequently contain a wide range of depths the threshold (`dd_factor`) to detect depth discontinuities has to be scaled accordingly. The pixel footprint is equal to the edge length if the neighboring pixels are at the same depth. The threshold defines what deviations from this *optimal* edge length are assumed to be plausible.

**Comment by sweeneychris** [comment]
@nmoehrle Thanks for the clarification! That makes more sense with the explanation.
