### ISSUE TITLE
Any plan to support PMVS-2?

### ISSUE THREAD

**Issue by jonghochoi** [simonfuhrmann/mve#268]
Hi,

I want to use the output of PMVS-2 as input for FSSR. PMVS-2 results are saved in 3 different files (dense.ply, dense.patch, and dense.pset). dense.ply contains 3D colored points for visualization purposes and the header information of the ply file was as follows:

ply
format ascii 1.0
comment VCGLIB generated
element vertex 99851
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 0
property list uchar int vertex_indices
end_header
... ...

However, FSSR's input samples must have the 'values' ply attribute (the scale of samples). So I couldn't input dense.ply into FSSR pipeline. Do you have advises to compute 'value' and 'confidence' per vertex or other methods? Thank you.

Best regards,
Choi

**Comment by simonfuhrmann** [comment]
Good question.

Unfortunately, there is no "good" way to compute the `value` attribute for every vertex. Optimally, this would the "physical" size of the sample in 3D space. If the point cloud doesn't contain any redundancy, it is approximately the distance to neighboring samples. Internally, PMVS could compute this value precisely.

Using the distance to neighboring samples isn't the correct way to compute this value since redundancy in the point could makes this value smaller than it actually is. But since PMVS doesn't produce a lot of redundant patches (in contrast to our MVS), I think using the average distance to the K nearest neighbors (try K=5?) will work.

If PMVS doesn't output a confidence value, just set this to `1.0`. There is no way to compute this after the fact. Instead PMVS should produce such a value based on the matching confidence.

**Comment by simonfuhrmann** [comment]
Closing this. Feel free to comment or reopen if there is an issue.
