### ISSUE TITLE
Questions about the floating scale surface reconstruction

### ISSUE THREAD

**Issue by hushanming** [simonfuhrmann/mve#271]
Hi,
I have read the two papers about the [ fssr algorithm](http://www.gcc.tu-darmstadt.de/home/proj/mve/index.en.jsp) on the offical website although I do not quite understand the algorithm.In the paper you have mentioned the concept of ‘’scale“，and I found in your _mve_ [code](https://github.com/simonfuhrmann/mve/blob/master/apps/scene2pset/scene2pset.cc#L271) you multiply the _scale_factor_ which value is 2.5.Colud you please explain what the meaning of the parameter?
Other questions:
If I have a data which have no _scale_ and no _confidences_,Can I  compute  the required scale only from the _.ply_ file or  more information about the data?

**Comment by simonfuhrmann** [comment]
In our code, FSSR samples are generated from triangulated depth maps. From a triangulated depth map, the scale (i.e., physical size in 3D space) for each sample (vertex) can be computed by averaging the length of edges emanating from the vertex.

Since the depth map has been computed using a MVS algorithm, the actual scale of the sample is a bit different. Because each reconstructed pixel in the depth map has been estimated using a patch-based comparison (NCC on patches of size 5x5 pixels in our MVS), the size of the patch needs to taken into account. This is where the scale factor of 2.5 is used -- it's the radius of the patch.

This is also explained in Section "6.2 Multi-View Stereo Data" in the FSSR paper.

**Comment by hushanming** [comment]
Thank you for your reply.

**Comment by hushanming** [comment]
Hi,
 I have another question about the "scale",if I want to compute the "scale" of the PLY file, such as the Stanford University _Bunny_  data,Should I create the depth maps for the _Bunny_ data to computed the "scale" ? What if the PLY file have no camera infos or other required information about  creating the depth maps? Does it have  other ways to get the value about the "scale"?
Thank you!

**Comment by simonfuhrmann** [comment]
The Stanford bunny is also provided as multiple PLY files which contain "range maps". These range maps are not exactly depth maps, but they are view-dependent meshes which can be transformed to a common coordinate system.

There is a tool `meshalign` in MVE which can convert the Stanford format to a bunch of overlapping meshes in a common coordinate system.

Whenever you have a bunch of overlapping meshes in a common coordinate system, you can use the `mesh2pset` tool, which turns the meshes into samples with scale information (based on the connectivity information) and computes confidence values (based on a mesh boundary condition). This is what you are looking for, and the ideal format to generate MVE samples. (It's essentially what we do with our depth maps, too.)
