### ISSUE TITLE
Surface reconstruction from oriented point cloud 

### ISSUE THREAD

**Issue by dobrina3** [simonfuhrmann/mve#298]
Dear Simon, 
I would like to test your Floating Scale Surface Reconstruction software on an oriented point cloud and not on a set of depth maps. 
My 3D points have already estimated normals but they do not have scale values. 
Could you please tell me how to estimate these scale values and if there is a tool coming with MVE allowing to do so ?   
Thanks in advance, 
D

**Comment by simonfuhrmann** [comment]
Hi, unfortunately, there is no tool that comes with MVE to estimate scale values. In fact, estimating scale values is impossible after the fact, e.g, after all depth maps have been merged into a single point cloud. The reason is that you cannot distinguish between redundancy and resolution. For example if you have a dense set of points, it could be either due to redundancy or due to high resolution.

So, how you should generate your scale values actually depends on the underlying data. 

 * If you have a non-redundant point set (uniform or not), you can use the sample spacing for the scale value. 
 * If you have a constant redundancy, you can use the sample spacing and divide by the "amount of redundancy" (i.e., 1 if you have no redundancy, 2 if you have twice as many measurements as necessary, etc). 
 * If you have varying redundancy, then you are screwed, because you cannot distinguish between redundancy and detail. The best you can do then is use the sample spacing and assume constant redundancy, which is what most reconstruction systems do (PSR, etc.).

In any case, you need a way to compute sample spacing, e.g., the average or median spacing to the K nearest neighbors, K=6 is reasonable. Or create an octree from your samples and use the cube sizes as scale value.

**Comment by dobrina3** [comment]
Hi, thank you very much for your clear explanation ! 
I will estimate the scales from the distances to the k-nearest neighbors, as you suggested.
