### ISSUE TITLE
What is the  resolution for the depth maps? how to get corresponding points between images and depth maps

### ISSUE THREAD

**Issue by wguo68** [simonfuhrmann/mve#301]
The guide said "MVS automatically chooses a resolution for the depth maps. 
what is the  resolution for the depth maps?
It is rarely useful to reconstruct at full resolution". If I want to get corresponding points between images and depth maps ,how to do this?

thanks

**Comment by simonfuhrmann** [comment]
The more correct statement would be: "`dmrecon` automatically chooses a reasonable scale for the depth maps."
It chooses a scale so that the image is below 1.5MP (call `dmrecon` without arguments to find this option). You can choose the scale yourself using the `-s` switch instead. Say a depth map has been reconstructed as scale `s`, the corresponding pixel `(x,y)` in the depth map maps to pixel `((x+0.5)*2^s-0.5, (y+0.5)*2^s-0.5)` in the color image.

**Comment by simonfuhrmann** [comment]
Ideally, you just down-scale the color-image (each scale down-scales the image by half) and make a 1:1 lookup. `dmrecon` automatically down-scales the images and places them in the view for you.

**Comment by wguo68** [comment]
thank you
