### ISSUE TITLE
Blending map

### ISSUE THREAD

**Issue by tmac1002** [simonfuhrmann/mve#336]
Hi, I used some UAV images to generate sparse point. However, the result map seemed blending. I am very confused. I just have no idea why this happened. Could you help me explain this situation or what exactly reasons caused this results. Thank you very much!
![blend_image](https://cloud.githubusercontent.com/assets/11924213/25466094/db06d13c-2b38-11e7-8b2b-ddda4ce17f86.JPG)

**Comment by simonfuhrmann** [comment]
Sure, that's easy to explain. The reconstruction is correct, it's the curvature of the earth.

No I'm just kidding. The reason why you see a bending is because the camera reconstruction is not accurate. The reconstructed geometry and the camera parameters are just estimations based on a model that is optimal with respect to certain assumptions that may not be accurate in practice. E.g., such assumptions include that the camera principle point is in the center of the image. Bundle adjustment will inevitably introduce some errors in both the geometry and camera parameters that will, over the course of several connected cameras, accumulate and cause a bending of the geometry. This is a common problem that is termed "reconstruction drift".

There are several solutions to reduce reconstruction drift. I believe @nmoehrle will be able to give you some advice, in particular, introducing survey points will effectively eliminate the drift but requires some effort on your side.

**Comment by simonfuhrmann** [comment]
@pmoulon, good x-posting catch :+1:

**Comment by tmac1002** [comment]
Thank you for your answer. And I also have a question about initial pair that why you don't set the first canonical camera constant in the bundle adjustment. I just think this camera should always be canonical form. But in your code you added this camera in the whole optimization.

**Comment by simonfuhrmann** [comment]
Well you still want to optimize for the initial camera intrinsics. And whether you also optimize the extrinsics or not doesn't really matter, does it? You can always transform the scene so that the first camera is in the origin. From an implementation standpoint, keeping the extrinsics of exactly one camera fixed in BA is not trivial.
