### ISSUE TITLE
Using MVE for photogrammetry with a stationary camera and a rotating subject?

### ISSUE THREAD

**Issue by JacobRoth** [simonfuhrmann/mve#345]
Hi all ! 

I'm using MVE to do some biology research - I'm creating 3D reconstructions of flower buds which are about 3cm long. All of our photography happens in a well-lit lab. The way I'd like to do this is to place the buds to be scanned on a rotation state and then move the stage a few degrees, take a photo, move it again, repeat. I set up a rotating stage to do this and took a bunch of photos. All of the photos (I've attached a <10MB subset in a zip file [here](https://github.com/simonfuhrmann/mve/files/1024095/jacobRothFlowerBudPhotos.zip), let me know if you want to see all of them and I can find a way to get them to you) contain only the bud or the surface of the stage, so from the camera's perspective, everything is moving. 

This should produce the same results as keeping the subject stationary and moving the camera, no? The problem is when I feed these images into `makescene` and then `sfmrecon`, sfmrecon basically fails, producing calculations for only a couple views.

Whereas if I do what should be equivalent, and move the camera around the subject and take photos that way, everything is fine and MVE can give me wonderful 3D results. It's just much less convenient from an automation standpoint, which is where we're ultimately headed with this project.

Is it possible to use MVE with a stationary camera and a rotating subject?

**Comment by nmoehrle** [comment]
Using a glass stand for the flower is a problem here, the reflection of the light creates a highlight that is identical if the angle between light and camera stays constant (which it does if you rotate around the axis of the stand) creating false matches. However, I am surprised that we cannot recover with overwhelming amount of features on the wooden base plate.

Your assumption that moving the camera around the object and rotating the object is identical holds only if you have complete defuse lighting and Lambertian materials. The lights reflection on the glass stand (the highlight) shows that these conditions are not met in your case.

My advise would be to change the stand, untreated wood like the base plate is a good material here, and diffusing the light as much as possible, we use softboxes in our photo lab.

Hope that helps, the flower bud looks amazing and I would love to see a reconstruction :-)

**Comment by flanggut** [comment]
The features on the wood won't match properly as the depth of field is super small and they constantly move into and out of focus. 

The lighting and material of the flower is probably the biggest problem. There's not a lot of texture on the pant and If you change the lighting with respect to the object many of the features will change their appearance (my guess is the object is also translucent to some extend). This is not something you would necessarily notice as a human. 
An extreme example would be a completely white object (e.g. a bone). The only features you can see are caused by lighting effects on the object. If you move the lighting relative to the object, i.e. rotate your table, it still looks like the same overall object to you, but locally all of the features change their appearance. This is what causes the feature matching to fail.

**Comment by pmoulon** [comment]
For "macro" photogrammetry often the best is to use a "White box"
https://www.amazon.com/gp/product/B01NBBXF5Y/

You can also:
- create a mask for each of your image (based on the green channel since your are using plants) in order to constraint the feature match to be on your object.

- or you can try to have a stationary object and use a device that make your camera turn around your object.

**Comment by simonfuhrmann** [comment]
Neat dataset. But I am also concerned that there are not enough features on the plant itself. So I am not sure how well a white box would work in this case. But generally, a white box is a pretty handy tool.

But as others already mentioned, moving the subject is not equivalent to moving the camera. Mainly because of lighting, and it makes a huge difference. Rotating the lights changes gradient directions, and gradients is what SIFT uses for matching. Be aware of that.

**Comment by simonfuhrmann** [comment]
You could try Pierre's SFM (OpenMVG), which generally performs better SfM reconstruction than our pipeline I would say, and then use the OpenMVG to MVE exporter and keep using MVE for `dmrecon` and the later steps.

**Comment by pmoulon** [comment]
@JacobRoth You can share me the dataset and I can play with it in order to see what I can obtain. Or provide feedback to you during your experiments.

**Comment by JacobRoth** [comment]
Hi again everyone!

I built a rotation stage with lights on it, then did the photogrammetry in a darkroom so that the rotation stage lights were the only light source. This allowed me to get some data with a stationary camera and a moving object! 

However, only for an opaque object. When I tired to do this with a flower bud SFMRECON failed. I suspect this is due to translucency, because in low lights it becomes apparent that the bud is in fact quite translucent. 

Is there any way to get around the translucency problem? Short of dying our object with ink, which I might resort to.

Also: @pmoulon I'd love to send you some data. What's the best way to get ~100MB of photos to you?

**Comment by pmoulon** [comment]
Hi @JacobRoth 
You can share it via "GDrive" here openmvg-team@googlegroups.com

You can use a metallic wire to support or suspend your object.

**Comment by pmoulon** [comment]
@JacobRoth Any new about the data sharing?
