### ISSUE TITLE
Comprehension of scale and confidence

### ISSUE THREAD

**Issue by Kano2** [simonfuhrmann/mve#353]
Hi,

I have trouble understanding some parts of the algorithm :
- the function depthmap_mesh_confidences in depthmap.cc compute confidence for each vertex, if I understand well, you give 0 to all borders vertexs, then 1/iterations, 2/iterations, ... to AdjacentVertexs. So more the vertexs are "inside", more there confidences are high.  Based on the line 521 : 
float conf = (float)current / (float)iterations, the confidences should be 0, 1/4, 2/4, 3/4 (you call mve::geom::depthmap_mesh_confidences(mesh, 4) in scene2pset). What I do not understand is that you execute meshclean with the parameter -t10 (so you test confs[i] > thresh, with thresh = 10) when the confidence always seems less than 1. What do I miss?

- I have also difficulties to understand the role of scale:  "Knowing scale allows us to reliably
identify redundancy in the samples and avoid intermingling data
captured at different scales", I found this in the paper "Floating Scale Surface Reconstruction". 
I have not found any more precise definitions, so I would like to know if you could give one.

- What is the purpose to use an octree to compute vertexs position in fssrecon ? I don't understand how the surface is reconstruct.

Thanks in advance,

Kano

**Comment by simonfuhrmann** [comment]
Hi,

1) The function you are describing assigns confidence to depth maps. Your description is accurate in that border veritices have confidence 0, then the low confidence is propagated inwards. Not sure about the exact numbers though. What meshclean does, however, is operating on the final surface fused by FSSR. These confidences are different. They are basically a weighted sum of ALL depth maps in a specific region. So confidence values sum up, e.g., if you average 20 depth maps, confidence can be as large as 20.

2) The scale of a sample describes the physical extent of a sample in 3D space. Scale does not give you information about redundancy per se, but knowing the sample positions AND the scale enables to infer information about redundancy. Think about this: A very dense set of samples could either be because of a very high resolution surface sampling (small scale values) or a very redundant low resolution surface sampling. Without scale you wouldn't know the difference.

3) The octree is just an acceleration structure. For every point in space, you could as well evaluate the reconstruction function (2) in the paper for all samples in the scene, it would just be extremely inefficient.

**Comment by Kano2** [comment]
Thank you very much for the clarification.

Kano
