### ISSUE TITLE
Background reconstructed

### ISSUE THREAD

**Issue by HelliceSaouli** [simonfuhrmann/mve#384]
Hello
Some times when i try to reconstruct  especially at lab environment dataset  like this one [Red-Dino-Toy](https://github.com/HelliceSaouli/GIBVH/blob/master/resources/Data%20sets/Toy%20Dinosaur/visualize/00.jpeg) the background is captured  and also get reconstructed so i ws wondering what are the solutions for this problem

 Thanks

**Comment by simonfuhrmann** [comment]
What exactly is the problem? You can specify a bounding box when calling `scene2pset` to get rid of some points (and you can use the AABB creator in UMVE to visualize the AABB beforehand). Alternatively, you can also use Meshlab to clean up the final mesh.

**Comment by HelliceSaouli** [comment]
![snapshot00](https://user-images.githubusercontent.com/10406314/31294940-aa9161c2-aad4-11e7-99ff-b655e8911fea.png)
This  is the problem even if i clean this i lost part of true mesh since the background and true mesh has the same confidence value computed in scene2pset. Creating AABB or using meshlab to remove it is tedious work.  but it seems there are no other solutions than these.

thank you

**Comment by simonfuhrmann** [comment]
Uh that doesn't look good. How many images are you using for reconstruction?

**Comment by HelliceSaouli** [comment]
36 image. scale -s2 the rest of parameters are default. well this in the eyes of MVE theoretically  correct because it is trying to reconstruct the the whole scene. but the result are not that accurate. XD

**Comment by simonfuhrmann** [comment]
I would assume that this issue goes away with more photos, like 150 or so. The problem is that it estimates the background at the wrong depth, which leads to all these problems. 

There is a feature in `scene2pset` that allows you to use masks. Just add a mask.png (1-channel image) to every view and use white for regions you want to keep, and pure black for regions you want to discard. It should be fairly straightforward to generate a mask for these images.
https://github.com/simonfuhrmann/mve/blob/master/apps/scene2pset/scene2pset.cc#L369
