### ISSUE TITLE
[Ques] Missing Point in Dense Point Cloud.

### ISSUE THREAD

**Issue by ManishSahu53** [simonfuhrmann/mve#396]
Hi,
I have 325 aerial images and I did SFM in openMVG. Then I used MVE to make dense point cloud. But I observed that there are a lot of patches missing in Dense Point Cloud. Can you tell me what to do in order to improve this? 
Thank You
![image](https://user-images.githubusercontent.com/27155127/35001233-60962ffc-fb0c-11e7-91d0-b43df5447005.png)

**Comment by flanggut** [comment]
It's hard to judge without more information. Is this result after running `meshclean`?
In any case you could try SMVS https://github.com/flanggut/smvs

**Comment by ManishSahu53** [comment]
No this is point cloud. Yes I have tried running SMVS also. Its better than this but still bad

**Comment by flanggut** [comment]
So usually something has to be really wrong if so many parts of the scene are missing. It could be the initial SfM reconstruction, so the camera parameters might be wrong - but usually aerial images work quite well so I would doubt that. It could also be a lack of overlap in the images, so you might just not have enough images of every part of the scene - but I also doubt that because its only a lot of small pieces that are missing.

If it is possible could you share some of the images that you used?

**Comment by ManishSahu53** [comment]
here are some of the images. 
https://drive.google.com/drive/folders/1TpgFuHN0cg4N2t1GKgGE51szwFTjZ4n_?usp=sharing

**Comment by flanggut** [comment]
Yeah, so `dmrecon` definitely expects more overlap, but you can get around that issue by setting `--local-neighbors=1`. 

The patch you uploaded reconstructed quite well for me with. Most of the holes you see are large trees, that are in general quite awkward to reconstruct. Some might work but maybe the also moved during the capture, which makes it practically impossible to find a consensus. You can ignore that and output some result, but MVE usually doesn't reconstruct geometry if it isn't reasonably sure that it's correct.

**Comment by ManishSahu53** [comment]
With this dmrecon setting (local-neighbour=1) wont it consider only 1 neighbour image rather than 4 by default?Wont this further reduce the 3D points?

**Comment by flanggut** [comment]
The problem is that most parts of the scene are only observed by one or two views, and with the regular setting `dmrecon` won't reconstruct these points because it only looks for points that have been observed by 4 or more neighbors. If you set the option it will only consider 1 neighbor, but that means it can actually reconstruct more points.

**Comment by ManishSahu53** [comment]
Oh. I get it. Will try to do this.

**Comment by ManishSahu53** [comment]
Hey @flanggut ,
I was reading about this problem and I think I found an good explanation about this in [Gupima](https://github.com/kysucix/gipuma) paper. He is tweaking the fusion parameters of depth map fusion step. The author says that The  fusion  parameters f , fang and f con filter out 3D points that are deemed unreliable, and thus balance accuracy against completeness of the multiview reconstruction.  Different applications require a different trade-off ( e.g ., computer graphics applications of ten prefer complete models, whereas in industrial metrology sparser,  but  highly  accurate  reconstructions  are  needed). This gives Gupima flexibility of choosing between completeness and accuracy. Do we have this kind of flexibility here? If not how can we add it?
