### ISSUE TITLE
How many photos of which size do you recommend at least?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#401]
I used a GoPro with 4K video and extracted the photos. I wonder, which minimal angle between shots is sufficient, ie smaller angles and more pictures don't contribute to better reconstruction.

**Comment by simonfuhrmann** [comment]
It depends what your goals are. If you want a global reconstruction with FSSR, the simple truth is that you can't really have "too many" photos. Even if the viewing angle between shots is very small, each photo contributes a depth map and, if the surface is sufficiently dense sampled, this adds lots of redundant information. Since depth maps reconstructed from photos are not incredibly accurate, more redundancy helps to find a more accurate average surface with lower error.

For a small object, 100 photos may be enough, but 1000 are better. And 2000 are even better. It boils down to how much effort are you willing to put into taking the photos, how long you can wait for a reconstruction, and how much memory your system has.

**Comment by ErfolgreichCharismatisch** [comment]
Especially memory is a problem over here.

**Comment by simonfuhrmann** [comment]
So the answer is: Use as many phones as possible within your limitations.

**Comment by ErfolgreichCharismatisch** [comment]
Currently I can handle two phones on two hands, but with enough practise, I could train my feet to reach max capacity.
