### ISSUE TITLE
Saving time by passing information about how photos were taken

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#402]
I move around the object and try to get a top and bottom view at the end. Is there a way to tell this to mve, for it to save time figuring it out itself?

**Comment by simonfuhrmann** [comment]
Well, unfortunately you can't. You could conceivably pass a matching matrix and tell the system which images to match, but we don't support providing such a matrix, and setting up such a matrix is probably more work that letting the system decide which photos to match.

I had to look because I though we had such a feature, but I think it was @stepankonrad who implemented something similar.
