### ISSUE TITLE
Perfect images that mve cannot handle

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#408]
I downloaded some CC0 images from http://www.zoosphere.net/sequence/153/Indeterminate/Indeterminate (Click the cloud icon below send feedback) and mve cannot handle it at all.

Why is that and how could I make mve handle those images?

**Comment by simonfuhrmann** [comment]
Because most of the frame is white, and the object itself doesn't have a lot of texture, and the bus's material is reflective. This is a challenging dataset. If the camera positions are known, you can try importing them and then run `featurerecon` instead of `sfmrecon`. But I doubt that this dataset will produce good results.

**Comment by ErfolgreichCharismatisch** [comment]
How do [they](https://sketchfab.com/tags/zoosphere) do it then?

**Comment by flanggut** [comment]
Try https://www.capturingreality.com

**Comment by ErfolgreichCharismatisch** [comment]
It is better to improve mve than using some other package as a solution. The right question you should ask yourself is: 

> how could I improve mve to be able to detect images of objects with white background?

**Comment by flanggut** [comment]
Yeah, but there is no easy solution and we don't have enough time to look into larger issues.

**Comment by ErfolgreichCharismatisch** [comment]
What, apart from money, would be a reasonable incentive for you to put some time into this issue?

**Comment by HelliceSaouli** [comment]
You have to know that  is impossible to have multi-view stereo reconstruction system which can deal with everything, especially passive methods. in this methods MVE, SMVS PMVS ..etc you are trying to infer multiple unknowns from only images so if you really need a detailed geometry use 3D scanners otherwise SMVS created by @flanggut  can recover far better geometry than mve

**Comment by simonfuhrmann** [comment]
Still waiting on @flanggut to integrate SMVS into MVE.

**Comment by HelliceSaouli** [comment]
is that so hard x') you can do it your self after all SMVS was born from MVE

**Comment by nmoehrle** [comment]
Nobody said it was hard but as posed in the according issue in raised the question whether it would be a good idea to put projects that are tightly coupled to MVE into an MVE organization.

And please when making such comments consider that this is an open source project maintained by people in their free time while juggling their job, family and whatever live throws at them...

**Comment by ErfolgreichCharismatisch** [comment]
> SMVS created by @flanggut can recover far better geometry than mve

Interesting. I assumed simonfuhrmann and flanggut to be colleagues who work together in a university, so I assumed them to have a fused code.

**Comment by HelliceSaouli** [comment]
@nmoehrle I know i know the community of MVE is top tier in computer vision i mean the amount of question you answered here is a proof how nice people you guys are. i was just joking and being sarcastic sorry :')

**Comment by ErfolgreichCharismatisch** [comment]
@HelliceSaouli Why don't you download the picture package and see if you can make mve or smvs reconstruct it?

**Comment by HelliceSaouli** [comment]
Ok i will see what i can do
