### ISSUE TITLE
How to thin the layers in point cloud when using MVS(dmrecon+scene2pset or SMVS)?

### ISSUE THREAD

**Issue by s-wtnb** [simonfuhrmann/mve#423]
As a result of doing MVS, there are thick "layers" in point cloud to generate from multiple photographs.
I want to know how to thin layers.
(There is no problem reducing the amount of point clouds.)

Please let me know if it is setting (argument), mve's code editing, different exe..., if you know something.

**example of layer thickness**
![pointcloud](https://user-images.githubusercontent.com/25291845/39282675-63d1940e-4945-11e8-9474-67ffe9a1dd53.jpg)

**Comment by simonfuhrmann** [comment]
This "thicknesses" is just noise due to inaccurate depth map measurement. You'd have to find a consensus surface, which is a problem that is usually solved by surface reconstruction algorithms. You could run `fssrecon` and throw away the triangles if you're not interested on the connectivity information.
