### ISSUE TITLE
Parallelizing MVE possible / documentation resources?

### ISSUE THREAD

**Issue by anfobi** [simonfuhrmann/mve#424]
Hello,

I apologize in advance if this forum is not the right place to ask questions; I didn't see any reference to a mailing list on the MVE website.

I am curious if the MVE SfM pipeline could be distributed via OpenMPI or a comparable clustering mechanism? I've read through the GSC+07 paper and it seems that the computationally expensive optimization aspects of the SfM and Multi View Stereo implementation only implicate small collections of neighborhood images used for stereo matching, but I haven't stepped through the entire process to understand all of the different processes at work here.

Also, are there any additional documentation resources beyond the API documentation? My use case doesn't require a good portion of the GSC+07 paper as my input dataset is from the same imager so no issue with varying resolutions and different types of cameras; I am attempting to reduce the total number of steps in the MVE SfM / MVS process to reduce the total time involved. I am also interested in utilizing SURF instead of the SIFT implementation referenced in the GSX+07 paper and I see reference to it in the API documentation but haven't been able to locate any man pages or ancillary docs for the command line utilities themselves.

Thanks in advance

**Comment by simonfuhrmann** [comment]
To get documentation for the command line options, call the tools without arguments. Unfortunately, SIFT/SURF can't be controlled using a command line flag. Change this line [1] to use `sfm::FeatureSet::FEATURE_SURF` to use SURF only, and recompile `sfmrecon`.

SFM itself can't be parallelized well except for what we already implement using OpenMP. Although matching could in theory run on several machines, we have no support for this, and adding it is not trivial. So you're stuck to one machine for this step. (@pmoulon, does OpenMVG support this?)

The `dmrecon` tool, however, can trivially be parallelized to multiple machines. Because it operates individually on depth maps, just log in to multiple machines and call `dmrecon` with a set of view IDs (`-l` flag, e.g., `-l0-99` on the first machine, `-l100-199` on the second machine, etc.). I assume the same is true for SMVS (@flanggut?).

The `scene2pset` can be used similarly (using the `-v` flag) to create multiple point clouds (one per machine). `fssrecon` can use multiple point sets as input, however, it must be executed on a single machine. Extensions to multiple machines are theoretically not too hard, but we can't provide support to implement this. (We don't take bigger feature requests.)

[1] https://github.com/simonfuhrmann/mve/blob/master/apps/sfmrecon/sfmrecon.cc#L96

**Comment by simonfuhrmann** [comment]
Closing. Feel free to reopen.

**Comment by flanggut** [comment]
> I assume the same is true for SMVS (@flanggut?).

Yes

**Comment by HelliceSaouli** [comment]
_dmrecon_ is hard to be parallelized on a pixel level since it is based on sophisticated aggregation approach which makes use of a Queue that holds pixels and each computed pixel depends on its neighbors. however there is a paper made by @simonfuhrmann  i guess where he tried to run _dmrecon_ on gpu

**Comment by namibj** [comment]
Plagued by the long runtimes on video capture, as well as the horrible performance of the std::set and std::map containers used in the tight loops, I'm currently trying to get dmrecon sufficiently fast to evaluate the reconstruction quality when combined with FSSR, as, judging by how the software spends it's time (a local path/neighbor walking, i.e., instead of saving the estimates of the neighbor pixels for later, just try them right away and keep some minimal state to fill the area, should yield somewhat close results at multiple times the speed, even on a CPU), which is currently still over 80% in the code handling the queue (and nothing else, not even preparing the data before filling the queue or so), with only about 5~8 % (much of the code is inlined, so it's not easy to tell what is queue overhead and what not) of the CPU cycles spend on actual patch computations.

I calculated that within the latency bounds reported by benchmarks, it should be possible to offload this awful task of deciding in what order to optimize patches, and maybe also where to derive the estimates from that are needed for the optimization loop to converge, but that one task might be better handled on the GPU itself due to the bandwidth/storage required for keeping track of the confidence values. Provided I find a way to connect an FPGA to the GPU with enough bandwidth and I did not grossly miscalculate anything, I predict multiple frames (2^12 * 2^11 ~ 8 MP) per second, up to about 50 or so for one AMD RX Vega 56 and a Genesys 2 FPGA board (not cheap, but easily worth it if it surpasses one frame per second at that resolution).

I'm not fixed on dmrecon, it just plays rather well with FSSR, and the results from the small data set I ran (~1200 pictures, but iirc L2 on the 6MP source files, and still not that high of a fillrate) are very promising, so that I want to see if the kind of capture I know I can get can be well digested by FSSR, after running it through a (likely patch-based) depth/normal reconstructor.
