### ISSUE TITLE
What do I need to do with lens distorted images for them to work with mve?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#427]
I did experiment a lot to get any gopro (hero 4) mode working with mve, but sadly, it didn't. Every time I use my mobile phone camera, it works well even though the resolution is lower than the GoPros. Even using argus for python and "defishing" it didn't work.

Even linear mode did not even work rudimentarily as well as the smartphone version.

To stop fishing in the dark, what do I need to do with lens distorted images for them to work with mve just as well?

**Comment by simonfuhrmann** [comment]
Sorry for the late reply. But I really don't know. I thought we experimented with Gopro cameras, and it just worked. The issue is that our initial guess for lens distortion is "no distortion" and we optimize from there. So if the distortion is way off, it will result in a bad reconstruction.

So "defishing" it sounds like a good approach. When you did that, did you make sure the resulting images still have the focal length in the EXIF tags?
