### ISSUE TITLE
Images with white backgrounds. 

### ISSUE THREAD

**Issue by theonlynick0430** [simonfuhrmann/mve#453]
I am attempting to perform photogrammetry using MVE with images created by rotating an object on a turntable rather than rotating the camera around the object. The images I took are against a uniform white background with ideal lighting. When I ran MVE on them, it created a object (PLY file) with zero vertices and faces. I assumed that the images having white backgrounds wouldn't affect the reconstruction process. Am I incorrect?

**Comment by simonfuhrmann** [comment]
Please post the console output. We have to figure out which part of the pipeline failed.

**Comment by theonlynick0430** [comment]
**SFM Output:** 

SSE2 accelerated matching is enabled.
SSE3 accelerated matching is enabled.
Initializing scene with 9 views...
Initialized 9 views (max ID is 8), took 3ms.
Computing image features...
View ID 0000 (1512x2016),  3180 features, took 2577 ms.
View ID 0001 (1512x2016),  2961 features, took 2525 ms.
View ID 0002 (1512x2016),  2429 features, took 2464 ms.
View ID 0003 (1512x2016),  2169 features, took 2480 ms.
View ID 0004 (1512x2016),  2301 features, took 2526 ms.
View ID 0005 (1512x2016),  2424 features, took 2525 ms.
View ID 0006 (1512x2016),  3089 features, took 2533 ms.
View ID 0007 (1512x2016),  3876 features, took 2635 ms.
View ID 0008 (1512x2016),  4169 features, took 2674 ms.
Computed 26598 features for 9 views (average 2955).
Computing features took 24059 ms.
Performing feature matching...
Pair (1,0) matched, 14 inliers, took 261 ms.
Pair (2,0) rejected, inliers below threshold of 12.
Pair (2,1) matched, 14 inliers, took 234 ms.
Pair (3,0) rejected, inliers below threshold of 12.
Pair (3,1) rejected, inliers below threshold of 12.
Pair (3,2) rejected, inliers below threshold of 12.
Pair (4,0) rejected, inliers below threshold of 12.
Pair (4,1) rejected, inliers below threshold of 12.
Pair (4,2) rejected, inliers below threshold of 12.
Pair (4,3) matched, 13 inliers, took 221 ms.
Pair (5,0) rejected, only 2 of 5 low-res matches.
Pair (5,1) matched, 12 inliers, took 245 ms.
Pair (5,2) rejected, inliers below threshold of 12.
Pair (5,3) rejected, inliers below threshold of 12.
Pair (5,4) matched, 15 inliers, took 214 ms.
Pair (6,0) rejected, inliers below threshold of 12.
Pair (6,1) rejected, inliers below threshold of 12.
Pair (6,2) rejected, inliers below threshold of 12.
Pair (6,3) rejected, inliers below threshold of 12.
Pair (6,4) rejected, inliers below threshold of 12.
Pair (6,5) matched, 12 inliers, took 235 ms.
Pair (7,0) rejected, inliers below threshold of 12.
Pair (7,1) matched, 12 inliers, took 274 ms.
Pair (7,2) matched, 12 inliers, took 261 ms.
Pair (7,3) rejected, inliers below threshold of 12.
Pair (7,4) rejected, inliers below threshold of 12.
Pair (7,5) rejected, only 4 of 5 low-res matches.
Pair (7,6) rejected, inliers below threshold of 12.
Pair (8,0) matched, 91 inliers, took 288 ms.
Pair (8,1) matched, 16 inliers, took 277 ms.
Pair (8,2) matched, 12 inliers, took 258 ms.
Pair (8,3) rejected, inliers below threshold of 12.
Pair (8,4) rejected, inliers below threshold of 12.
Pair (8,5) rejected, inliers below threshold of 12.
Pair (8,6) rejected, inliers below threshold of 12.
Pair (8,7) rejected, inliers below threshold of 12.
Found a total of 11 matching image pairs.
Matching took 8533 ms.
Saving pre-bundle to file...
Cleanup: Released 0 embeddings in 0 of 9 views.
Initializing camera intrinsics...
Computing feature tracks...
Propagating track IDs...
Removing tracks with conflicts... deleted 0 tracks.
Colorizing tracks...
Created a total of 209 tracks.
Searching for initial pair...
  Pair   0,  8:   92 matches,   69 H-inliers (75%),  7.26 pair angle
Using views 0 and 8 as initial pair.
Triangulated 92 new tracks, rejected 0 bad tracks.
  Splitted 0 new tracks.
Deleted 0 of 92 tracks (0.00%) above a threshold of 0.0123601.
Running full bundle adjustment...
BA: MSE 1.61775e-05 -> 5.1589e-07, 40 LM iters, 1323 CG iters, 21ms.
Camera   0, focal length: 0.74286 -> 0.93670, distortion: -5.10794 16.18514
Camera   8, focal length: 0.74286 -> 0.50265, distortion: -1.09471 1.36918
No valid next view.
SfM reconstruction finished.
SfM reconstruction took 224 ms.
Creating bundle data structure...
Writing bundle (9 cameras, 92 features): /Users/nikhilsridhar/Desktop/white-output/synth_0.out...
Saving view /Users/nikhilsridhar/Desktop/white-output/views/view_0000.mve
Saving view /Users/nikhilsridhar/Desktop/white-output/views/view_0008.mve

**DMRecon Output:**

MVE Depth Map Reconstruction (built on Nov  9 2018, 20:31:48)
Initializing scene with 9 views...
Initialized 9 views (max ID is 8), took 4ms.
Reading Photosynther file (9 cameras, 92 features)...
Reconstructing all views...
Reconstructing /Users/nikhilsridhar/Desktop/white-output
  !.......!
Reconstruction took 1454ms.
Saving views back to disc...
Saving views to MVE files... done.

**Scene2Pset Output:**

Using depthmap "depth-L2" and color image "undist-L2"
Initializing scene with 9 views...
Initialized 9 views (max ID is 8), took 2ms.
Processing view "Image1" (with colors)...
Processing view "Image9" (with colors)...
Writing final point set (0 points)...
Writing PLY file (0 verts, with colors, with normals, with confidences, with values, 0 faces)... done.

As you can see, the outputted PLY file has zero vertices and faces. The images I used can be found here: https://drive.google.com/drive/folders/1q_5yDq61mIdc7zMG2XngMbCK7tBMZNUd?usp=sharing

**Comment by simonfuhrmann** [comment]
It seems your images don't have enough overlap. See how it computes thousands of features per image? But most of the good pairs only match with a handful of inliers. This probably means the images are too far apart. That leads to a successfully reconstructed initial pair, but no other view could be added. 

`dmrecon` won't reconstruct depth maps if it cannot find enough neighboring views. Since there are only two views reconstructed, it won't do anything.

For our pipeline, if you want a good reconstruction, I recommend you take A LOT more photos. Also, if you're just taking photos on a "ring" around the object, you will get a lot better reconstructions if you add more views in a dome/sphere around the object as you will significantly reduce matching ambiguity.

**Comment by theonlynick0430** [comment]
Thank you so much for your help. I am now using a image set with triple the amount of images. MVE successfully generated over 30 views this time. However, the final mesh still looks nothing like the actual object. The image set I used can be found here: https://drive.google.com/drive/folders/1bi_MskxFx9Jc_cXEkbIjUHlvvtI8YO-D?usp=sharing
The outputted mesh clean file looks like the following:
<img width="556" alt="screen shot 2018-11-23 at 12 59 20 pm" src="https://user-images.githubusercontent.com/27570998/48960219-a53c0980-ef1f-11e8-8cab-92daae67748a.png">
Any help is greatly appreciated.

**Comment by simonfuhrmann** [comment]
You're facing a few issues here. First, people don't have a lot of features required for successful reconstruction. Skin, clothing and hair is relatively texture-less, and will not reconstruct well. On top of that, your images have varying degree of quality; some have motion blur, some have more noise than others, etc. Because the scene doesn't have a strong texture, you have to rely on image quality more then usual. Also, you subject moves. Even the slightest movement will lead to bad things, maybe matches will be rejected as outliers, or in the best case you just get very, very noisy depth maps.

That being said, reconstructing humans is very challenging. To give you an idea, check out Infinite Realities work at http://ir-ltd.net/. These guys have a setup on a whole different level with dozens of high-res cameras that all expose in the same millisecond, and still what they get out of image-based reconstruction is far from perfect and requires LOTS of manual touch-up.
