### ISSUE TITLE
 Is there a way to clean the scene2pset output ply file according to the confidence ?

### ISSUE THREAD

**Issue by MartinAlexParis** [simonfuhrmann/mve#454]
Hello,
I am a new user of  the mve pipeline and i am impressed by the quality of your work.

The command i use is: scene2pset.exe -ddepth-L2  -iundist-L2  -n -s -c

Usually scene2pset provides a good ply file ..but... there are too many incorrect points.
Is there a way to clean the ply file according to the confidence ?
Or is there a config to increase the quality of dmrecon + scene2pset ?
Thank you

**Comment by simonfuhrmann** [comment]
No there is not. But you could try using `meshclean -t0.5 --no-clean --component-size=0 in.ply out.ply`. Let me know if that works.

**Comment by simonfuhrmann** [comment]
Note that this is not using `dmrecon` confidences, as they are not very meaningful.
If you have a very dense image set, you could play around with the `--local-neighbors` option for `dmrecon` and see if that increases quality. If you have a controlled capture setup, also try `--nocolorscale`.

**Comment by simonfuhrmann** [comment]
If you don't specify `--no-clean` the tool will attempt to clean slivers and caps, which are typical marching cubes triangulation artifacts. Since you don't have triangles and just points, it will complain that there are no triangles. If you don't specify `--component-size=0`, it will remove connected components that are smaller than the specified amount. Since you don't have connected components, because you don't have triangles, it will remove all isolated points.

**Comment by simonfuhrmann** [comment]
You can also call all tools with `--help` or without arguments to see the help text.
