### ISSUE TITLE
How to keep the normals of a Point Cloud after cleaning it with meshclean ?

### ISSUE THREAD

**Issue by MartinAlexParis** [simonfuhrmann/mve#455]
Hello,
I am cleaning the point could  produced by scene2pset using the command 
 meshclean -t0.5 --no-clean --component-size=0 in.ply out.ply
as described here : https://github.com/simonfuhrmann/mve/issues/454

But the normals are removed. Is there a way to keep the normals ?

**Comment by simonfuhrmann** [comment]
Right. The default behavior of `meshclean` is to not save normals, because this tool is intended to be used on meshes. And for meshes, you usually don't have to store normals because you can recompute them from the triangles when loading the mesh. In your case, you have to explicitly tell the tool to save normals.

There is no command line argument for it. But you can edit the code and add

    ply_opts.write_vertex_normals = true;

to this location: https://github.com/simonfuhrmann/mve/blob/master/apps/meshclean/meshclean.cc#L190
