### ISSUE TITLE
how to initialize SFM with cameras poses and orientations priors

### ISSUE THREAD

**Issue by vholod** [simonfuhrmann/mve#466]
Hi,
Is there a way to initialize SFM with cameras poses and orientations priors?
Thanks,

**Comment by simonfuhrmann** [comment]
I don't think you can provide camera extrinsics without writing your own application that drives the sfm library. But there is some support for providing intrinsics, see here: https://github.com/simonfuhrmann/mve/issues/154

**Comment by HelliceSaouli** [comment]
@simonfuhrmann  you should add this feature, everyone is asking for it

**Comment by simonfuhrmann** [comment]
Hi, unfortunately there isn't. There is a way to initialize cameras with intrinsics (see the other issue about this), but not with extrinsics. Because the latter requires a significantly different reconstruction approach. I know I should implement this feature, but it's probably not going to happen any time soon. Sooooorry!
