### ISSUE TITLE
Can the software handle such environment as follow? Why I get so bad result?

### ISSUE THREAD

**Issue by philleer** [simonfuhrmann/mve#468]
Hi, @simonfuhrmann 
I want to get the reconstruct model using my own photos captured in some environment.
Just like this:
[image1](https://github.com/philleer/program_test/blob/master/opencv_test/04281.jpg)
[image2](https://github.com/philleer/program_test/blob/master/opencv_test/2b_59.jpg)
when i use it, i ask someone standing in the middle of the environment and take several photos via the cameras around it on the pole, but the result i get by the MVE pipeline is very awful and i can just get half of the scene.
Is the lighting too complicated or background too mess, or what else?
What should i do to handle such problem?
Appreciate for you reply.

**Comment by simonfuhrmann** [comment]
Yes, that's not going to work properly, mainly because of lack of texture in the scene and repetitive structures in the background. I made experiments with similar setups before. At the very least you need pre-calibrated cameras (i.e., SfM is not going to work properly) and don't use the built in MVS but try SMVS (https://github.com/flanggut/smvs) due to lack of texture.

**Comment by philleer** [comment]
Thanks for your prompt response.
Then I have tried SMVS, and the result is a little better, still not very good though.
Maybe I should try precalibrate my cameras as your suggestion.
Thank you very much.

**Comment by philleer** [comment]
Well, not very related to this issue, do you have any advice about object reconstruction with repetitive structures in the background?
I have tried subtracting background with opencv and just keep the object region in the picture, but I cannot reconstruct it correctly. I don't know why, maybe i did not make a good configuration.

**Comment by simonfuhrmann** [comment]
Subtraction sounds like a very good approach. Take pictures without the subject and then with the subject. Then subtract those regions that have not changed. Since you're removing even more features, camera pre-calibration becomes even more important. Once you have put your camera calibration into the `meta.ini` file in each view, use the `featurerecon` app to reconstruct the features required by MVS.

Since both the shipped MVS and SMVS rely on features in the scene, maybe both of these approaches are not ideal for your scenes. A brute force plane sweeping comes to mind...

**Comment by simonfuhrmann** [comment]
BTW, a cheap way of pre-calibrating your cameras is to still use MVE's SfM, but don't use a scene with a person in it. Put big texture-rich targets (e.g., many cardboard boxes with SIFT-friendly patterns) in the scene. A pile of boxes like this [1] with a texture sticked on the sides like this [2] or this [3].

[1] https://atlas-content-cdn.pixelsquid.com/assets/938710393910465684/jpeg-600/G12.jpg
[2] https://rulebyart.com/products/cellular-foam-bubble-texture
[3] https://www.tonytextures.com/free-natural-stone-wall-texture-photo-gallery/

**Comment by philleer** [comment]
Got it.
I'll try `featurerecon` as you said. And a brute force plane sweeping? I will explore it and have a try as well.
Very appreciated for your suggestion ^_^
