### ISSUE TITLE
How to save depth maps as images (e.g. bmp or jpg)? 

### ISSUE THREAD

**Issue by vholod** [simonfuhrmann/mve#482]
Hi,
How to save depth maps as images in the __dmreacon__ code?
or 
How to convert depth maps ( for example depth-L.mvei type ) to jpg (or another common format) format?

Many Thanks,
Vadim

**Comment by simonfuhrmann** [comment]
Depth maps are stored in their own file format because they are not ordinary images. They are float images. If you just want a visualization of the depth map, you can use UMVE (view inspect tab), and you can also store that visualization as a common PNG or JPEG image (photo icon).

If you need to visualize a lot of depth maps you will have to write your own tool, reading the `.mvei` images using MVE's libraries (or write your own parser, it's trivial and the file format is documented in the Wiki) and do the conversion from float image to byte image yourself.

**Comment by vholod** [comment]
Thank you very much
