### ISSUE TITLE
fssrecon with normals as output

### ISSUE THREAD

**Issue by talkenig** [simonfuhrmann/mve#500]
Hi, 
I noticed fssrecon does not write normals to the file, although it is provided with normals and can easily compute those from the local implicit representations.
The question is whether there is a way to get an output with normals. I saw issue #455 so I know how to handle it with meshclean.
I know I can compute them from the mesh, providing the triangles have consistent direction, but it would be easier to just keep them.

**Comment by simonfuhrmann** [comment]
Normals are not stored because they are implicitly given by the geometry and easy to compute, hence a waste a storage space.

If you still want to write normals, put the same code from #455 you referenced into the fssrecon.cc file where the mesh is saved. I'm not sure if fssrecon ever computes the normals of the output mesh, so you may have to call ensure_normals() on the mesh before saving it.
