### ISSUE TITLE
mask filtered all points

### ISSUE THREAD

**Issue by zhixiongzuo** [simonfuhrmann/mve#511]
Dear Sir ,thanks for you excellent work. When I use scene2pset with command "scene2pset -mmask -F0 scene point.ply", I get 0 point pointcloud,bacause of filtered all points. (I put mask.png under each view directory.if 
 I don't use "-mmask" , I get a dense pointcloud ).
My masks' info:  
Colorspace: Gray
  Colors: 3
  Colormap entries: 256
  Colormap:
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: none
    png:IHDR.color-type-orig: 0
    png:IHDR.color_type: 0 (Grayscale)
Any suggestion?

**Comment by simonfuhrmann** [comment]
MVE expects a 1-channel mask and all it does is project 3D points to the mask, and reject points that project onto purely black pixels. Maybe the mask does not work as you expect it to work, which is understandable, because it's a little strange. 

The mask does NOT apply to a single view, but to the whole scene. That is, it does NOT just clip pixels from one depth map, but projects ALL points into ALL masks and rejects all points that project onto black.

If you want to apply a per-view mask, you'll have to modify your depth maps directly, and then use `scene2pset`.

Does that answer the question?

**Comment by zhixiongzuo** [comment]
Thanks for your reply. 
Simply description my problem: I have 360 views and for each view I have image and foreground mask, I want to reconstruct foreground. so first i use mask to put background in image to be black. then I put processed images to colmap to get nvm. after that I use dmrecom and scene2pset to get pointcloud. But I find that there are many black outliers belong with foreground，so i add param --mask in scene2pset，want to filter black outliers，just find filtered all points.... 
Your suggestions I can use mask to process depthmap，more detail？ I know dmrecon will generate depth-L0，but I don't know exactly how to do，because it's not an image.

**Comment by simonfuhrmann** [comment]
I suggest you write a small program that loads, for each view, the depth map and the mask, and invalidate pixels in the depth map (by setting them to 0) as indicated by your mask.

I am afraid there is no ready-to-use solution for your case, and you will have to write some code to achieve your goal.

**Comment by zhixiongzuo** [comment]
ok ,I will try it. Thanks for your suggestion.
