### ISSUE TITLE
[Question] Can not load jpg files

### ISSUE THREAD

**Issue by CaptainEven** [simonfuhrmann/mve#527]
![image](https://user-images.githubusercontent.com/9303747/98650082-5f2e1980-2373-11eb-950c-de458cbcf952.png)

**Comment by simonfuhrmann** [comment]
Have you tried using `/` instead of `\`?

**Comment by CaptainEven** [comment]
@simonfuhrmann Yes, the error remains.
![image](https://user-images.githubusercontent.com/9303747/98753415-42d7be80-23ff-11eb-98d2-6b51d61a2b05.png)

**Comment by simonfuhrmann** [comment]
I'm wondering if 1. MVE has been compiled without JPG support, or 2. this is actually not a JPG file. Can you try opening one of the image and check the actual file format?

Otherwise i don't know what the issue is, sorry. Does MVE work with other images, e.g. the datasets available from here?

https://www.gcc.tu-darmstadt.de/home/proj/mve/

**Comment by CaptainEven** [comment]
@simonfuhrmann The jpg images are extracted from a video shot by smartphone, which is done by extracting each frame of the video using OpenCV video capture(save to disk with ".jpg" suffix).

**Comment by CaptainEven** [comment]
@simonfuhrmann The jpg images are extracted from a video shot by smartphone, which is done by extracting each frame of the video using OpenCV video capture(save to disk with ".jpg" suffix).

**Comment by simonfuhrmann** [comment]
Does it load other JEPG images from a different source, like the one provided above?

**Comment by CaptainEven** [comment]
@simonfuhrmann It's ok for other jpg files like shot alone by a smartphone other than extracted from videos. Thanks for your excellent work and nice reply. I 'll dig into the code and debug some stuff.
